### PR TITLE
Add @iov/cli module paths to REPL context

### LINKED ISSUE #328: Docs to run with @iov/cli don't work out of the box
Roman tried to install from npm and that didn't work, he had to install a few more packages manually.

Let's reproduce this on a clean vm (not dev machine) and verify what commands are needed and update documentation to make this process smoother for those not cloning the repo and building it.

Please assign to Ethan when there is a clear way to reproduce problem.

### PR DESCRIPTION
**Pull request by webmaster128**
Resolves  #328

### CODE REVIEW

**Comment by webmaster128** [comment]
okay, found a solution :)

**Comment by webmaster128** [comment]
Linked the issue this PR resolves. I think this is sufficient to get the idea.

**Comment by ethanfrey** [comment]
Ahh, i missed that. Thanks.

**Comment by webmaster128** [comment]
> Ahh, i missed that. Thanks.

I added it after the review. It was not there before

**Pull request merged**
