### PR TITLE
Update ganache-cli to ^6.2.2

### LINKED ISSUE #546: Update ganache-cli to 6.2+
when https://github.com/trufflesuite/ganache-cli/issues/595 is fixed

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #546

### CODE REVIEW

**Comment by webmaster128** [comment]
Oh wow, that pulls in tons of dependencies. We should consider installing ganache via docker …

**Comment by davidmurdoch** [comment]
@webmaster128 I know `iov-core` is yarn only, so this probably doesn't affect you: the `npm-shrinkwrap.json` file in v6.2.2 had an issue with some npm versions, so I've released v6.2.3.

As for as the dependency issues, we're planning on moving back to a webpacked build (6.1.* was all webpacked) in the very near future which will get rid of nearly all of these dependencies.

Just curious... is the concern with # of dependencies due to the increased installation time?

**Comment by webmaster128** [comment]
@davidmurdoch thanks, then we go to 6.2.3 straight, even if it should not change anything.

> Just curious... is the concern with # of dependencies due to the increased installation time?

I was surprised but thinking about it again, I don't see any real issue with the number of dependencies.

**Comment by webmaster128** [comment]
All green, thanks @davidmurdoch!

**Pull request merged**
