### PR TITLE
Add synchronous, isolated semi-pseudo-random generator

### PR DESCRIPTION
**Pull request by ethanfrey**
Crypto/random is secure but async. It is also overkill for identifiers for test cases.
Math.random is vulnerable to reseeding.
I didn't feel comfortable adding another dep https://github.com/davidbau/seedrandom especially as it globally modifies the Math variable.

Rudi's comment https://github.com/iov-one/iov-core/pull/332#pullrequestreview-154697853 and insistence on slack encouraged me to add something myself.

Hope this is okay....

### CODE REVIEW

**Comment by rudi-cilibrasi** [comment]
i think it's better to use a solution that has received peer review for many years

https://www.npmjs.com/package/random-js

**Comment by rudi-cilibrasi** [comment]
the problems with semirandom are: 1. non-standard api 2. not well documented 3. hard to find seeding (as it's not standard) 4. hard to believe in (not widely tested/reviewed) 5. hard to use elsewhere. if we include a non-offensive prng module from npm we will gain a lot more functionality in addition to points 1-4.

**Comment by rudi-cilibrasi** [comment]
we also can reduce risk for our users by not making a(nother) unsafe prng ```For anything important, please use Random.getBytes() from ./libsodium.ts.```

**Comment by rudi-cilibrasi** [comment]
credible docs here https://github.com/ckknight/random-js

**Comment by rudi-cilibrasi** [comment]
`semi-random` is a real technical term also already but with different meaning i believe https://arxiv.org/abs/1805.02259

**Comment by ethanfrey** [comment]
Closing due to popular demand.

**Comment by webmaster128** [comment]
:+1: for using a lib here

**Pull request closed without merging**
