### PR TITLE
Bech32 cleanup

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by willclarktech** [comment]
Why do we need the custom types?

**Comment by webmaster128** [comment]
> Why do we need the custom types?

1. Because the types from @types are wrong in many aspects
2. It allows us to pass binary data as Uint8Array directly instead of creating a copy to Buffer

**Comment by willclarktech** [comment]
Is it worth submitting a PR to the DefinitelyTyped project?

**Comment by webmaster128** [comment]
> Is it worth submitting a PR to the DefinitelyTyped project?

I'm sumitting it to the project directly: https://github.com/bitcoinjs/bech32/pull/29#issuecomment-516733500

**Pull request merged**
