### PR TITLE
Eslint: no-explicit-any

### PR DESCRIPTION
**Pull request by willclarktech**
Partially addresses #876

### CODE REVIEW

**Comment by willclarktech** [comment]
One option would be to enable it on a per-file basis in any situation where we might be dealing with unknown data (e.g. parsers etc)?

**Comment by webmaster128** [comment]
This makes all
- type guards
- error callbacks
- parsers

"bad" in the sense of linter judgement and pollutes great valid code with exceptions. I'd very much prefer to not introduce a rule that does not add a good amount of value.

**Comment by willclarktech** [comment]
Makes sense.

**Comment by webmaster128** [comment]
Thanks

**Pull request merged**
