### PR TITLE
Support AmendElectionRuleThreshold/Quorum proposals

### PR DESCRIPTION
**Pull request by willclarktech**
Part of #1112

### CODE REVIEW

**Comment by webmaster128** [comment]
Could you run this through the linter once #1123 is merged? Looks like no change needed but just in case

**Comment by webmaster128** [comment]
Wait a second – this will crash in `packages/iov-bns/src/encode.ts` at

```
  } else {
    throw new Error("Got unsupported type of ProposalOption");
  }
```

right? I'd prefer to merge this when the whole flow works. Otherwise we need an extra ticket to ensure we don't forget about that.

**Comment by willclarktech** [comment]
Ah yes, sorry, missed that step.

**Comment by willclarktech** [comment]
We need to wait for weave 0.19 for this.

**Pull request merged**
